version: "3.8"

services:
  # backend api
  api:
    build: .
    command: uvicorn src.api.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - .:/usr/src/api
    ports:
      - "8004:8000"
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
    depends_on:
      - database
  # application database
  database:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql/data
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    ports:
      - "3320:3306"

# data volumes
volumes:
  mysql_data: