version: "3.8"

services:
  # backend api
  api:
    build: .
    command: uvicorn src.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - .:/usr/src/api
    ports:
      - "8004:8000"
    env_file:
      - .env
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      TESTING: ${TESTING}
    depends_on:
      - database

  # application database
  database:
    image: mysql:8.0
    command: --innodb_use_native_aio=0
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${SQL_DATABASE}
      MYSQL_USER: ${SQL_USER}
      MYSQL_PASSWORD: ${SQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${SQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"

# data volumes
volumes:
  mysql_data: